// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { PlayersData } from "./../index.sol";

/**
 * @title ITasksSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITasksSystem {
  function addTask(string memory description) external returns (bytes32 key);

  function completeTask(bytes32 key) external;

  function resetTask(bytes32 key) external;

  function deleteTask(bytes32 key) external;

  function addPlayer(address player, uint x, uint y) external;

  function getPlayer(address player) external view returns (PlayersData memory playerdata);

  function capturePlayer(address player) external;

  function uncapturePlayer(address player) external;

  function movePlayer(address player, uint dx, uint dy) external;
}
